# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('url', models.URLField(default=None, max_length=255, unique=True, verbose_name='链接')),
                ('pub_time', models.DateTimeField(default=None, verbose_name='发布时间')),
                ('source', models.CharField(default=None, max_length=50, verbose_name='来源')),
                ('images', models.TextField(default=None, verbose_name='图片链接')),
            ],
            options={
                'verbose_name_plural': '新闻',
                'verbose_name': '新闻',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=100, verbose_name='站点名')),
                ('start_urls', models.TextField(verbose_name='入口页面')),
                ('allow_domains', models.TextField(default=None, verbose_name='允许的域名（正则表达式）')),
                ('url_rule', models.CharField(default=None, max_length=255, verbose_name='url提取规则（正则表达式）')),
                ('title_rule_reg', models.CharField(default=None, max_length=255, verbose_name='title提取规则（正则表达式）')),
                ('title_rule_css', models.CharField(default=None, max_length=255, verbose_name='title提取规则（css选择器）')),
                ('title_rule_xpath', models.CharField(default=None, max_length=255, verbose_name='title提取规则（xpath选择器）')),
                ('pub_time_rule_reg', models.CharField(default=None, max_length=255, verbose_name='发布时间提取规则（正则表达式）')),
                ('pub_time_rule_css', models.CharField(default=None, max_length=255, verbose_name='发布时间提取规则（css选择器）')),
                ('pub_time_rule_xpath', models.CharField(default=None, max_length=255, verbose_name='发布时间提取规则（xpath选择器）')),
                ('source_rule_reg', models.CharField(default=None, max_length=255, verbose_name='来源提取规则（正则表达式）')),
                ('source_rule_css', models.CharField(default=None, max_length=255, verbose_name='来源提取规则（css选择器）')),
                ('source_rule_xpath', models.CharField(default=None, max_length=255, verbose_name='来源提取规则（xpath选择器）')),
                ('content_rule_reg', models.CharField(default=None, max_length=255, verbose_name='内容提取规则（正则表达式）')),
                ('content_rule_css', models.CharField(default=None, max_length=255, verbose_name='内容提取规则（css选择器）')),
                ('content_rule_xpath', models.CharField(default=None, max_length=255, verbose_name='内容提取规则（xpath选择器）')),
                ('comment_num_rule_reg', models.CharField(default=None, max_length=255, verbose_name='评论数提取规则（正则表达式）')),
                ('comment_num_rule_css', models.CharField(default=None, max_length=255, verbose_name='评论数提取规则（css选择器）')),
                ('comment_num_rule_xpath', models.CharField(default=None, max_length=255, verbose_name='评论数提取规则（xpath选择器）')),
                ('images_rule_reg', models.CharField(default=None, max_length=255, verbose_name='图片提取规则（正则表达式）')),
                ('images_rule_css', models.CharField(default=None, max_length=255, verbose_name='图片提取规则（css选择器）')),
                ('images_rule_xpath', models.CharField(default=None, max_length=255, verbose_name='图片提取规则（xpath选择器）')),
            ],
            options={
                'verbose_name_plural': '新闻站点',
                'verbose_name': '新闻站点',
            },
        ),
    ]
