# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='comment_num_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='评论数提取规则（css选择器）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='comment_num_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='评论数提取规则（正则表达式）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='comment_num_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='评论数提取规则（xpath选择器）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='content_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='内容提取规则（css选择器）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='content_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='内容提取规则（正则表达式）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='content_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='内容提取规则（xpath选择器）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='images_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='图片提取规则（css选择器）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='images_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='图片提取规则（正则表达式）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='images_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='图片提取规则（xpath选择器）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='pub_time_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='发布时间提取规则（css选择器）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='pub_time_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='发布时间提取规则（正则表达式）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='pub_time_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='发布时间提取规则（xpath选择器）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='source_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='来源提取规则（css选择器）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='source_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='来源提取规则（正则表达式）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='source_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='来源提取规则（xpath选择器）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='title提取规则（css选择器）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='title提取规则（正则表达式）'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='title提取规则（xpath选择器）'),
        ),
    ]
