# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsModel', '0002_auto_20170809_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='allow_domains',
            field=models.TextField(default=None, verbose_name='允许的域名 正则 '),
        ),
        migrations.AlterField(
            model_name='site',
            name='comment_num_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='评论数 css '),
        ),
        migrations.AlterField(
            model_name='site',
            name='comment_num_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='评论数 正则 '),
        ),
        migrations.AlterField(
            model_name='site',
            name='comment_num_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='评论数 xpath '),
        ),
        migrations.AlterField(
            model_name='site',
            name='content_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='内容 css '),
        ),
        migrations.AlterField(
            model_name='site',
            name='content_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='内容 正则 '),
        ),
        migrations.AlterField(
            model_name='site',
            name='content_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='内容 xpath '),
        ),
        migrations.AlterField(
            model_name='site',
            name='images_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='图片 css '),
        ),
        migrations.AlterField(
            model_name='site',
            name='images_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='图片 正则 '),
        ),
        migrations.AlterField(
            model_name='site',
            name='images_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='图片 xpath '),
        ),
        migrations.AlterField(
            model_name='site',
            name='pub_time_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='发布时间css '),
        ),
        migrations.AlterField(
            model_name='site',
            name='pub_time_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='发布时间正则 '),
        ),
        migrations.AlterField(
            model_name='site',
            name='pub_time_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='发布时间xpath '),
        ),
        migrations.AlterField(
            model_name='site',
            name='source_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='来源 css '),
        ),
        migrations.AlterField(
            model_name='site',
            name='source_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='来源 正则 '),
        ),
        migrations.AlterField(
            model_name='site',
            name='source_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='来源 xpath '),
        ),
        migrations.AlterField(
            model_name='site',
            name='title_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='title css '),
        ),
        migrations.AlterField(
            model_name='site',
            name='title_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='title 正则 '),
        ),
        migrations.AlterField(
            model_name='site',
            name='title_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='title xpath '),
        ),
        migrations.AlterField(
            model_name='site',
            name='url_rule',
            field=models.CharField(default=None, max_length=255, verbose_name='url 正则 '),
        ),
    ]
