# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsModel', '0004_auto_20170809_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment_url',
            field=models.URLField(default=None, max_length=255, verbose_name='评论URL'),
        ),
        migrations.AddField(
            model_name='news',
            name='site',
            field=models.CharField(default=None, max_length=50, verbose_name='站点'),
        ),
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(default=None, max_length=255, verbose_name='源URL'),
        ),
        migrations.AddField(
            model_name='site',
            name='not_allowed_domains',
            field=models.TextField(default=None, verbose_name='不允许的域名 正则 '),
        ),
    ]
