# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsModel', '0005_auto_20170815_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url_rule_css',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='url css '),
        ),
        migrations.AlterField(
            model_name='site',
            name='url_rule_reg',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='url 正则 '),
        ),
        migrations.AlterField(
            model_name='site',
            name='url_rule_xpath',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='url xpath '),
        ),
    ]
