# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsModel', '0008_auto_20170815_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='crawl_deep',
            field=models.IntegerField(blank=True, default=2, verbose_name='爬取深度'),
        ),
    ]
