# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='关键词')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '登录用户',
                'verbose_name_plural': '登录用户',
            },
        ),
        migrations.CreateModel(
            name='WeChatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读量')),
                ('url', models.URLField(default=None, max_length=255, unique=True, verbose_name='链接')),
                ('pub_time', models.DateTimeField(default=None, verbose_name='发布时间')),
                ('nickname', models.CharField(default=None, max_length=100, verbose_name='nickname')),
                ('alias', models.CharField(default=None, max_length=100, verbose_name='alias')),
                ('round_head_img', models.URLField(default=None, max_length=100, verbose_name='round_head_img')),
                ('ori_head_img_url', models.URLField(default=None, verbose_name='ori_head_img_url')),
                ('msg_desc', models.CharField(default=None, max_length=200, verbose_name='msg_desc')),
                ('msg_source_url', models.URLField(default=None, verbose_name='msg_source_url')),
            ],
            options={
                'verbose_name': '微信文章',
                'verbose_name_plural': '微信文章',
            },
        ),
        migrations.CreateModel(
            name='WeChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='昵称')),
                ('alias', models.CharField(max_length=100, verbose_name='别名')),
                ('service_type', models.IntegerField(default=1, verbose_name='服务类型')),
                ('fakeid', models.CharField(default=None, max_length=100, unique=True, verbose_name='biz')),
                ('round_head_img', models.URLField(default=None, max_length=500, verbose_name='头像')),
                ('crawl_history', models.BooleanField(default=False, verbose_name='是否爬取历史文章')),
                ('crawled_history', models.BooleanField(default=False, verbose_name='是否爬取过历史文章')),
                ('monitored', models.BooleanField(default=False, verbose_name='是否监控最新文章')),
                ('description', models.CharField(default=None, max_length=255, verbose_name='描述')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '微信公众号',
                'verbose_name_plural': '微信公众号',
            },
        ),
        migrations.AddField(
            model_name='wechatdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeChatModel.WeChatUser'),
        ),
    ]
