# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WeChatModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatdata',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='wechatdata',
            name='url',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='fakeid',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='round_head_img',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
