# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeChatModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatdata',
            name='ori_head_img_url',
            field=models.URLField(default=None, max_length=500, verbose_name='ori_head_img_url'),
        ),
        migrations.AlterField(
            model_name='wechatdata',
            name='round_head_img',
            field=models.URLField(default=None, max_length=500, verbose_name='round_head_img'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='描述'),
        ),
    ]
