# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeChatModel', '0002_auto_20170802_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatdata',
            name='alias',
            field=models.CharField(default=None, max_length=100, verbose_name='作者biz'),
        ),
        migrations.AlterField(
            model_name='wechatdata',
            name='msg_desc',
            field=models.CharField(default=None, max_length=500, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='wechatdata',
            name='msg_source_url',
            field=models.URLField(default=None, verbose_name='原文链接'),
        ),
        migrations.AlterField(
            model_name='wechatdata',
            name='nickname',
            field=models.CharField(default=None, max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='wechatdata',
            name='ori_head_img_url',
            field=models.URLField(default=None, max_length=500, verbose_name='作者头像'),
        ),
        migrations.AlterField(
            model_name='wechatdata',
            name='round_head_img',
            field=models.URLField(default=None, max_length=500, verbose_name='作者头像'),
        ),
    ]
