# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeChatModel', '0003_auto_20170804_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatdata',
            name='msg_source_url',
            field=models.URLField(default=None, max_length=500, verbose_name='原文链接'),
        ),
    ]
