# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeChatModel', '0004_auto_20170804_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='crawled',
            field=models.BooleanField(default=False, verbose_name='是否爬取过'),
        ),
    ]
